### PR TITLE
./configure

### PR DESCRIPTION
**Pull request by shadowwalkersb**

### CODE REVIEW

**Comment by shadowwalkersb** [comment]
ping @jamesmbell for review

**Review by mbellphd — APPROVED** [review]
While I approve in principle, I'm concerned that Docker might require more maintenance than a generic build strategy (i.e. 3 computers, each running a different OS).

**Comment by shadowwalkersb** [comment]
Not sure I understand the concern here. This is a recipe produced by conda-forge tools. It is run on different CI servers and the built packages are uploaded to anaconda.org/cryoem. All automatic. There is no maintenance on our side. Especially once the packages are uploaded, since ftgl is not actively developed anymore, I think.

**Comment by mbellphd** [comment]
Do we all need to understand how to use docker in the (hopefully unlikely) event that the build breaks? I'm concerned that future developers, some of whom have little programming experience prior to graduate school, may struggle with this in the same way we've had to wrestle with the current build system. If you think this is the easiest strategy, then let's do it. I'm just indicating that I'm a proponent of whatever is the easiest for novice programmers to handle (or learn if they have to).

**Comment by sludtke42** [comment]
Ok, no idea what docker is.
----------------------------------------------------------------------------
Steven Ludtke, Ph.D.
Professor, Dept. of Biochemistry and Mol. Biol.                Those who do
Co-Director National Center For Macromolecular Imaging	           ARE
Baylor College of Medicine                                     The converse
sludtke@bcm.edu  -or-  stevel@alumni.caltech.edu               also applies
http://ncmi.bcm.edu/~stevel

**Comment by shadowwalkersb** [comment]
> I'm just indicating that I'm a proponent of whatever is the easiest for novice programmers to handle (or learn if they have to).

Build systems are not for novices, apparently. If this setup is problematic, manual ftgl builds and uploads are always welcome. Any volunteeres?

**Comment by shadowwalkersb** [comment]
Here is an overview of `conda-smithy`, https://github.com/conda-forge/conda-smithy#overview, the tool used to produce this. Docker is simply what conda-forge uses internally for Linux builds. No need to know what it is or what it does for this repository.

**Pull request merged**
